version: '2'

services:
  service2_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service2_go
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - service2_go_net

  service2_backend:
    build: .
    depends_on:
      - service2_go_db
    environment:
      SERVICE2_GO_MYSQL_HOST: service2_go_db
      SERVICE2_GO_MYSQL_DBNAME: service2_go
      SERVICE2_GO_MYSQL_USER: service2_go
      SERVICE2_GO_MYSQL_PASSWORD: service2_go
    ports:
      - "4102:4102"
    restart: always
    networks:
      - service2_go_net

networks:
  service2_go_net:
    driver: bridge
