http:
  port: '4102'
  host: '127.0.0.1'

logger:
  log_level: 'info'

db:
  driver: postgres
  data_source: postgres://postgres:postgres@ctf_training_platform_db:4112/ctf01d_training_platform?sslmode=disable
