http:
  port: '4102'
  host: 'localhost'

logger:
  log_level: 'debug'

db:
  driver: postgres
  data_source: postgres://postgres:postgres@localhost:4112/ctf01d_training_platform_test?sslmode=disable
