http:
  port: '4102'
  host: '0.0.0.0'

logger:
  log_level: 'warn'

db:
  driver: postgres
  data_source: postgres://postgres:postgres@ctf_training_platform_db:4112/ctf01d_training_platform?sslmode=disable
